version: '3.6'
services:
    api:
        build: .
        container_name: alemarcha-api-clean
        working_dir: /home/alemarcha-back
        logging:
            driver: 'json-file'
        ports:
            - 3000:3000
        command: >
            bash -c "npm install && npm run debug"
        volumes:
            - ./:/home/alemarcha-back
            - ./node_modules:/home/alemarcha-back/node_modules
        depends_on:
            - db
            - redis
    redis:
        image: redis
        container_name: alemarcha-redis-clean
        logging:
            driver: 'json-file'
        ports:
            - 6379:6379
        depends_on:
            - db
    db:
        image: mysql:5.7.18
        container_name: alemarcha-db-clean
        working_dir: /var/lib/mysql
        command: mysqld --sql_mode=""
        environment:
            MYSQL_DATABASE: test
            MYSQL_ROOT_PASSWORD: alemarcha
            MYSQL_USER: root
            MYSQL_USER_PASSWORD: alemarcha
        logging:
            driver: 'json-file'
        ports:
            - 3306:3306
        volumes:
            - mysql:/var/lib/mysql

volumes:
    mysql:
    node_modules: